module Algos::Template
	@@templates = 
	{
		"805lasalle.com" => {
			layout: "rentcafe_sites_scrape(response, url, data)",
			name: "Eight O Five",
			neighborhood: "River North",
			url: "https://www.805lasalle.com",
			address: "805 North LaSalle Drive Chicago, IL 60610",
			state: "Illinois",
			zip: "60610",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'td-card-name\']").text.strip.gsub("Apartment: ", "")',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'td-card-rent\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(u.xpath(".//td[@class=\'td-card-available\']").text.strip.gsub("Date:", ""))'
		},
		"landmarkconservancy.com" => {
			layout: "rentcafe_sites_scrape(response, url, data)",
			name: "Landmark Conservancy",
			neighborhood: "Downtown",
			url: "https://www.landmarkconservancy.com",
			address: "9301 Old Bee Caves Road, Austin, TX 78735",
			state: "Texas",
			zip: "78735",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'td-card-name\']").text.strip.gsub("Apartment: ", "")',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'td-card-rent\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(u.xpath(".//td[@class=\'td-card-available\']").text.strip.gsub("Date:", ""))'
		},
		"elmstreetplaza.com" => {
			layout: "rentcafe_sites_scrape(response, url, data)",
			name: "Elm Street Plaza",
			neighborhood: "Gold Coast",
			url: "https://www.elmstreetplaza.com",
			address: "1130 N Dearborn St Chicago, IL 60610",
			state: "Illinois",
			zip: "60610",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//div[@id=\'availApts\']//div[@class=\'card\']")',
			aptNo: 'u.xpath(".//h3[@class=\'h5 card-title\']/span").text&.strip',
			unit_price: 'parse_rent(u.xpath(".//p[@class=\'card-subtitle mb-2 text-muted\']").text.strip)',
			unit_moveIn: nil,
		},
		"asburyplaza.com" => {
			layout: "rentcafe_sites_scrape(response, url, data)",
			name: "Asbury Plaza",
			neighborhood: "River North",
			url: "https://www.asburyplaza.com",
			address: "750 North Dearborn Chicago, IL 60654",
			state: "Illinois",
			zip: "60654",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//div[@id=\'availApts\']//div[@class=\'card\']")',
			aptNo: 'u.xpath(".//h3[@class=\'h5 card-title\']/span").text&.strip',
			unit_price: 'parse_rent(u.xpath(".//p[@class=\'card-subtitle mb-2 text-muted\']").text.strip)',
			unit_moveIn: nil
		},
		"trioapartmentsaustin.com" => {
			layout: "rentcafe_sites_scrape(response, url, data)",
			name: "Trio",
			neighborhood: "Downtown",
			url: "https://www.trioapartmentsaustin.com",
			address: "2317 S. Pleasant Valley Road, Austin, TX 78741",
			state: "Texas",
			zip: "78741",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'td-card-name\']").text.strip.gsub("Apartment: ", "")',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'td-card-rent\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(u.xpath(".//td[@class=\'td-card-available\']").text.strip.gsub("Date:", ""))'
		},
		"wolfpointwest.com" => {
			layout: "luxury_living_table_scrape(response, url, data)",
			name: "Wolf Point West",
			neighborhood: "River North",
			url: nil,
			address: "343 W Wolf Point Plaza, Chicago, IL 60654",
			state: "Illinois",
			zip: "60654",
			floor_plans_loop: nil,
			fp_name: 'u.xpath(".//td[@class=\'layout\']").to_a[0].text&.strip',
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: 'parse_bed_new(u.xpath(".//td[@class=\'layout\']").to_a[0].text&.strip)',
			fp_bath: 'parse_bath(u.xpath(".//td[@class=\'bathrooms hidden-xs\']")[0].text).to_f',
			fp_sqft: 'only_numbers(response.xpath(".//ul[@class=\'list-inline layout\']/li[3]").text).to_i',
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			floor_plan_image: 'u.xpath(".//td[@class=\'floorplan hidden-xs\']/a")[0].attributes["href"].value',
			units_loop: 'response.xpath(".//table/tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'unit\']").to_a[0].text&.strip',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'price\']").to_a[0].text&.strip)',
			unit_moveIn: nil
		},
		"wolfpointeast.com" => {
			layout: "luxury_living_table_scrape(response, url, data)",
			name: "Wolf Point East",
			neighborhood: "River North",
			url: nil,
			address: "313 W Wolf Point Plaza, Chicago, IL 60654",
			state: "Illinois",
			zip: "60654",
			floor_plans_loop: nil,
			fp_name: 'u.xpath(".//td[@class=\'layout\']").to_a[0].text&.strip',
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: 'parse_bed_new(u.xpath(".//td[@class=\'layout\']").to_a[0].text&.strip)',
			fp_bath: 'parse_bath(u.xpath(".//td[@class=\'bathrooms hidden-xs\']")[0].text).to_f',
			fp_sqft: 'only_numbers(response.xpath(".//ul[@class=\'list-inline layout\']/li[3]").text).to_i',
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			floor_plan_image: 'u.xpath(".//td[@class=\'floorplan hidden-xs\']/a")[0].attributes["href"].value',
			units_loop: 'response.xpath(".//table/tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'unit\']").to_a[0].text&.strip',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'price\']").to_a[0].text&.strip)',
			unit_moveIn: nil
		},
		"goodnight-ranch-rentcafewebsite.securecafe.com" => {
			layout: "goodnight_ranch_rentcafe_algo(response, url, data)",
			name: "Bridge at Goodnight Ranch",
			neighborhood: "Southeast",
			url: nil,
			address: "Alderman Dr Austin, TX 78747",
			state: "Texas",
			zip: "78747",
			floor_plans_loop: 'response.xpath("//ul[@id=\'floorplansLink\']/li")',
			fp_name: 'response.xpath("//div[@class=\'tab-pane row-fluid active\']//h2").text.gsub("\n", "").strip',
			fp_rentMin: 'only_numbers(response.xpath("//div[@class=\'tab-pane row-fluid active\']//table//tr[4]/td[2]").text).to_i',
			fp_rentMax: 'only_numbers(response.xpath("//div[@class=\'tab-pane row-fluid active\']//table//tr[4]/td[2]").text).to_i',
			fp_bed: 'parse_bed_new(response.xpath("//div[@class=\'tab-pane row-fluid active\']//table//tr[1]/td[2]").text)',
			fp_bath: 'parse_bath(response.xpath("//div[@class=\'tab-pane row-fluid active\']//table//tr[2]/td[2]").text).to_f',
			fp_sqft: 'only_numbers(response.xpath("//div[@class=\'tab-pane row-fluid active\']//table//tr[3]/td[2]").text).to_i',
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: "response.xpath(\"//div[@class='tab-pane row-fluid active']//button\").text",
			floor_plan_image: 'response.xpath("//div[@class=\'tab-pane row-fluid active\']//img").first.values.last',
			units_button: "//div[@class='tab-pane row-fluid active']//button[@data-selenium-id='ApplyNow']",
			units_loop: 'response.xpath(".//table/tbody/tr")',
			aptNo: 'u.xpath(".//td[@data-label=\'Apartment\']").text.strip',
			unit_price: 'parse_rent(u.xpath(".//td[@data-label=\'Sq.Ft.\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(pattern_match(u.xpath(".//td[@data-label=\'Action\']//input").first.values.last, /MoveInDate=(\d{1,2}\/\d{1,2}\/\d{4})/))',
		},
	}
	
	def self.get(domain)
		@@templates[domain] || nil
	end
end