module Algos::Template
	@@templates = 
	{
		"805lasalle.com" => {
			name: "Eight O Five",
			neighborhood: "River North",
			url: "https://www.805lasalle.com",
			address: "805 North LaSalle Drive Chicago, IL 60610",
			state: "Illinois",
			zip: "60610",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'td-card-name\']").text.strip.gsub("Apartment: ", "")',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'td-card-rent\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(u.xpath(".//td[@class=\'td-card-available\']").text.strip.gsub("Date:", ""))'
		},
		"landmarkconservancy.com" => {
			name: "Landmark Conservancy",
			neighborhood: "Downtown",
			url: "https://www.landmarkconservancy.com",
			address: "9301 Old Bee Caves Road, Austin, TX 78735",
			state: "Texas",
			zip: "78735",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//tbody/tr")',
			aptNo: 'u.xpath(".//td[@class=\'td-card-name\']").text.strip.gsub("Apartment: ", "")',
			unit_price: 'parse_rent(u.xpath(".//td[@class=\'td-card-rent\']").text.strip)',
			unit_moveIn: 'prase_date_mddyyyy(u.xpath(".//td[@class=\'td-card-available\']").text.strip.gsub("Date:", ""))'
		},
		"elmstreetplaza.com" => {
			name: "Elm Street Plaza",
			neighborhood: "Gold Coast",
			url: "https://www.elmstreetplaza.com",
			address: "1130 N Dearborn St Chicago, IL 60610",
			state: "Illinois",
			zip: "60610",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//div[@id=\'availApts\']//div[@class=\'card\']")',
			aptNo: 'u.xpath(".//h3[@class=\'h5 card-title\']/span").text&.strip',
			unit_price: 'parse_rent(u.xpath(".//p[@class=\'card-subtitle mb-2 text-muted\']").text.strip)',
			unit_moveIn: nil,
		},
		"asburyplaza.com" => {
			name: "Asbury Plaza",
			neighborhood: "River North",
			url: "https://www.asburyplaza.com",
			address: "750 North Dearborn Chicago, IL 60654",
			state: "Illinois",
			zip: "60654",
			floor_plans_loop: nil,
			fp_name: nil,
			fp_rentMin: nil,
			fp_rentMax: nil,
			fp_bed: nil,
			fp_bath: nil,
			fp_sqft: nil,
			fp_sqftMin: nil,
			fp_sqftMax: nil,
			fp_is_available: nil,
			units_loop: 'response.xpath(".//div[@id=\'availApts\']//div[@class=\'card\']")',
			aptNo: 'u.xpath(".//h3[@class=\'h5 card-title\']/span").text&.strip',
			unit_price: 'parse_rent(u.xpath(".//p[@class=\'card-subtitle mb-2 text-muted\']").text.strip)',
			unit_moveIn: nil
		},

	}
	
	def self.get(domain)
		@@templates[domain] || nil
	end
end